### ISSUE TITLE
Validations would be useful!

### ISSUE THREAD

**Issue by larspetrus** [JeffBelgum/configclasses#1]
The basic implementation is obviously a function that takes the value and returns `True` or `False`.

In the spirit of making things easy to enter and read, alternative notations could be...

- A lambda: `lambda x : x < 40`
- A range: `range(3, 10)`
- A list of allowed values. Like an enum type without having to make the enum: `[2, 4, 6, 8]`
- A string of a boolean Python expression to be evaluated with `eval()`: `3 < value < 10`

**Comment by JeffBelgum** [comment]
@larspetrus This is a useful feature that I'll add when I get the chance. I think that lambdas/functions can be easily accommodated by adding a validator keyword argument to the field function. Range and lists are both iterables. It makes sense to add a convenience validation function that allows the user to pass in any iterable and check if it contains the configuration value found.
